In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(type(a),a.shape)



<class 'numpy.ndarray'> (3,)


In [ ]:
a[0]=5
print(a)

[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
print(b.shape)

(2, 3)


In [ ]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b=np.ones((1,2))

In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((2,2))
print(e)

[[0.1721718  0.87177673]
 [0.14847062 0.79746981]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [ ]:
print(a)
print(b)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


In [ ]:
row_r1 = a[1,:]
row_r2 = a[1:2, :]
row_r3 =a[[1], :]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
print(row_r3,row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1,col_r1.shape)
print()
print(col_r2,col_r2.shape)

[77  6 10] (3,)

[[77]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)



(3, 2)


In [ ]:
print(a[[0, 0], [1, 1]])


[2 2]


In [ ]:
print(np.array([a[0, 1], a[0, 1]]))


[2 2]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0, 2, 0, 1])
print(b)
print(a[:, b])


[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [ ]:
a[np.arange(4), b] += 10
print(a)


[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)
print(bool_idx)


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[bool_idx])

[3 4 5 6]


In [ ]:
print(a[a > 2])


[3 4 5 6]


In [ ]:
x = np.array([1, 2])
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x / y)
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(v.shape, w.shape)
print(v.dot(w))#9*11+10*12
print(np.dot(v, w))

print(x.dot(y))#

(2,) (2,)
219
219
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [ ]:
for i in range(4):
  y[i, :] = x[i, :] + v
  print(y)

[[2 2 4]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[2 2 4]
 [5 5 7]
 [0 0 0]
 [0 0 0]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [ 0  0  0]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
vv = np.tile(v, (4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np
x=np.array([[2,3,4],[36,72,18],[-1,2,3],[23,24,12]])
v=np.array([1,0,1])
y=v+x
print(y)


[[ 3  3  5]
 [37 72 19]
 [ 0  2  4]
 [24 24 13]]


In [ ]:
v = np.array([10,8,36])
w = np.array([43,59])
print(np.reshape(v,(3,1))*w)

[[ 430  590]
 [ 344  472]
 [1548 2124]]


In [ ]:
x=np.array([[40,53,23],[20,43,12]])
print(x+v)
print((x.T + w).T)

[[50 61 59]
 [30 51 48]]
[[ 83  96  66]
 [ 79 102  71]]


In [ ]:
print(x*2)

[[ 80 106  46]
 [ 40  86  24]]
